server:
  port: 8087
  context-path: /hanoa
leader:
  CEO: 韩沛毅
  CFO: 袁安然
  value: ${random.value}
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.3.48/hanoa
      username: root
      password: loveu588
